### ISSUE TITLE
[1.6.6] [db] SQL logic error: no such column: Sort (1)

### ISSUE THREAD

**Issue by PhilETaylor** [axllent/mailpit#107]
Just noticed this when running the docker container today

```
mysites-mailhog       | ERRO[2023/05/04 11:25:05] [db] SQL logic error: no such column: Sort (1)
mysites-mailhog       | ERRO[2023/05/04 11:26:05] [db] SQL logic error: no such column: Sort (1)
mysites-mailhog       | ERRO[2023/05/04 11:27:05] [db] SQL logic error: no such column: Sort (1)
mysites-mailhog       | ERRO[2023/05/04 11:28:05] [db] SQL logic error: no such column: Sort (1)
```

**Comment by axllent** [comment]
Hmmm, is it running with an existing database, or a temporary one? If existing, is it possible that more than one Mailpit instance is running using the same database, and that this error message is coming from an older version of Mailpit? The Sort column had been replaced and I'm fairly sure there should be no references to Sort in the code.

**Comment by PhilETaylor** [comment]
sorry should have said this is running as a docker container - so totally new 1.6.6 container instantiated by docker-compose 
```
  mailhog.mysites.guru:
    container_name: 'mysites-mailhog'
    image: axllent/mailpit
    ports:
      - "25:1025"
      - "1080:8025"
```
