### ISSUE TITLE
Docker Image fails to run with MP_DATA_FILE set

### ISSUE THREAD

**Issue by tminich** [axllent/mailpit#134]
First let me prefix that I'm not well-versed in Docker, so this might be because I'm doing something wrong. But, to my understanding of the docs, this should be working.

Here is the service from my `docker-compose.yml`:
```yaml
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: "mailpit"
    environment:
      - TZ="Europe/Berlin"
      - MP_DATA_FILE="/data/mailpit.db"
    restart: always
    ports:
      - '1025:1025'
      - '9000:8025'
    networks:
      - proxy
    volumes:
      - './data/mailpit:/data'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

The service keeps restarting logging
```
2023-06-28 12:08:10 ERRO[2023/06/28 10:08:10] unable to open database file: out of memory (14)
```

**Comment by axllent** [comment]
I got the same ~ though `- MP_DATA_FILE=/data/mailpit.db` (without quotes) works fine. It must be a docker-compose thing :)

**Comment by axllent** [comment]
I don't use docker-compose - but from what I read the syntax should actually be different: https://docs.docker.com/get-started/08_using_compose/

```yaml
    environment:
      TZ: Europe/Berlin
      MP_DATA_FILE: /data/mailpit.db
```

**Comment by tminich** [comment]
Ah thanks, I did not expect that to matter XD.

**Comment by mbuchner** [comment]
Don't think this is only the configuration style - since v1.15.1it is also not working for me. I didn't test v1.16.

v1.17.0 also displays this error to me - same setting worked with v1.15.1!

I use it  with compose: 
```
  mailpit:
    image: axllent/mailpit:v1.17.0
    environment:
      MP_UI_AUTH: 'user:password'
      MP_WEBROOT: 'fakemail'
      MP_MAX_MESSAGES: 500
      MP_DATABASE: /data/mailpit.db
    ports:
      - 1025:1025/tcp
      - 8025:8025/tcp
```

and Kubernetes:
```
...
      containers:
        - image: axllent/mailpit:v1.17.0
          name: my-fakemail
          env:
            - name: MP_UI_AUTH
              value: "user:password"
            - name: MP_WEBROOT
              value: "fakemail"
            - name: MP_MAX_MESSAGES
              value: "1000"
            - name: MP_DATABASE
              value: "/data/mailpit.db"
          ports:
            - containerPort: 1025
            - containerPort: 8025
....
....
```

Both are not working anymore - showing:
time="2024/04/20 19:09:13" level=error msg="[db] unable to open database file: out of memory (14)"
