### ISSUE TITLE
White screen when using a docker container with nginx proxy

### ISSUE THREAD

**Issue by gbalatckii** [axllent/mailpit#137]
Hi all,
I would like to use Mailpit on our dev environment and for this I use a docker container and I set up a nginx proxy. When I navigate to Mailpit I see a white screen. Can anyone tell me what the problem could be? Thank you!

Best regards,
Georgii

![Bildschirmfoto 2023-06-30 um 15 50 08](https://github.com/axllent/mailpit/assets/57895385/6ff2ca88-542a-4bd7-b9a7-1452de8bbfae)
![Bildschirmfoto 2023-06-30 um 15 50 18](https://github.com/axllent/mailpit/assets/57895385/2cb2fb2d-6ac3-4b9a-927b-47c3dc899e66)
<img width="838" alt="Bildschirmfoto 2023-06-30 um 15 50 41" src="https://github.com/axllent/mailpit/assets/57895385/1df63a40-e920-47a0-aae2-bf828f94a858">

**Comment by axllent** [comment]
What does the response for the app css and app.js return?

**Comment by gbalatckii** [comment]
@axllent 

# CSS
```css
<!DOCTYPE html><html lang="en"><head> <meta charset="utf-8"> <title>LenoClient</title> <base href="/"> <meta name="viewport" content="width=device-width, initial-scale=1"> <link rel="icon" type="image/x-icon" href="favicon.ico"> <style>html,body {
    margin: 0;
    padding: 0
}

html {
    box-sizing: border-box
}

*,*:before,*:after {
    box-sizing: inherit
}

html {
    background-color: #fff;
    font-size: 16px;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    min-width: 300px;
    overflow-x: hidden;
    overflow-y: scroll;
    text-rendering: optimizeLegibility;
    -webkit-text-size-adjust: 100%;
    text-size-adjust: 100%
}

body {
    font-family: BlinkMacSystemFont,-apple-system,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,Helvetica,Arial,sans-serif
}

body {
    color: #4a4a4a;
    font-size: 1em;
    font-weight: 400;
    line-height: 1.5
}

html,body {
    width: 100vw;
    height: 100vh;
    background-color: #eff1fa
}

</style><link rel="stylesheet" href="styles.dd426706f04b972c.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.dd426706f04b972c.css"></noscript></head> <body> <app-root></app-root> <script src="runtime.b87219bda1547c35.js" type="module"></script><script src="polyfills.e4381df6a608e04b.js" type="module"></script><script src="main.61db170c05832fbc.js" type="module"></script> </body></html>
```

# JS
```HTML
<!DOCTYPE html><html lang="en"><head>
  <meta charset="utf-8">
  <title>LenoClient</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>html,body{margin:0;padding:0}html{box-sizing:border-box}*,*:before,*:after{box-sizing:inherit}html{background-color:#fff;font-size:16px;-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;min-width:300px;overflow-x:hidden;overflow-y:scroll;text-rendering:optimizeLegibility;-webkit-text-size-adjust:100%;text-size-adjust:100%}body{font-family:BlinkMacSystemFont,-apple-system,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,Helvetica,Arial,sans-serif}body{color:#4a4a4a;font-size:1em;font-weight:400;line-height:1.5}html,body{width:100vw;height:100vh;background-color:#eff1fa}</style><link rel="stylesheet" href="styles.dd426706f04b972c.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.dd426706f04b972c.css"></noscript></head>
<body>
  <app-root></app-root>
<script src="runtime.b87219bda1547c35.js" type="module"></script><script src="polyfills.e4381df6a608e04b.js" type="module"></script><script src="main.61db170c05832fbc.js" type="module"></script>

</body></html>
```
