### ISSUE TITLE
Remote storage

### ISSUE THREAD

**Issue by ulexxander** [axllent/mailpit#254]
Hello, we really like this project and use it everyday on our project,
deploying it to dynamic staging environments on Kubernetes for each GitLab Merge (Pull) request.
We have a lot of them.

While our application is stateless and uses database as a storage, Mailpit is not and uses local SQLITE database,
which requires us to create PersistentVolume for each Merge Request to be able to persist Mailpit data on this environment.
We would like to avoid creating disk for each Merge Request, it would simplify infrastructure and improve performance.

Do you have any plans on implementing any remote storage, that's not bound to local filesystem?

What do you think about https://rqlite.io ?
I could try to contribute and implement it.
It seems that it is compatible and implementing it as an alternative storage should be easy.

**Comment by axllent** [comment]
Hi @ulexxander. I'm wondering if there might be an easier way for you to solve this issue. Could you not just run a dedicated Mailpit server and send mail via SMTP directly to that instead? It would mean all mail from each client ends up in the same mailbox, however that can potentially be addressed by using tags or similar.

To implement a secondary/alternative storage will (in my opinion) not be easy, as Mailpit was never designed to cater for that, so I fear a huge rewrite would be necessary to make this possible - I don't think it will be easy or quick. That being said, if you were willing to do the work and are somehow able to integrate rsqlite as an optional alternative storage, then I have no objection.

I'm keen to discuss this further before you get started though, as I suspect there may already be easy solutions already possible without resorting to any Mailpit rewrites.

**Comment by ulexxander** [comment]
@axllent Thanks for explanation!

Actually proof-of-concept persisting data in rqlite was quite simple
and I was able to persist and display mailbox from rqlite :smile: 

```diff
diff --git a/internal/storage/database.go b/internal/storage/database.go
index 540d67c..7f79984 100644
--- a/internal/storage/database.go
+++ b/internal/storage/database.go
@@ -18,6 +18,10 @@ import (
 
        // sqlite (native) - https://gitlab.com/cznic/sqlite
        _ "modernc.org/sqlite"
+       // rqlite (remote) - https://github.com/rqlite/gorqlite
+       // https://rqlite.io/
+
+       _ "github.com/rqlite/gorqlite/stdlib"
 )
 
 var (
@@ -51,9 +55,9 @@ func InitDB() error {
 
        var err error
 
-       dsn := fmt.Sprintf("file:%s?cache=shared", p)
+       dsn := "http://localhost:4001?disableClusterDiscovery=true"
 
-       db, err = sql.Open("sqlite", dsn)
+       db, err = sql.Open("rqlite", dsn)
        if err != nil {
                return err
        }
@@ -62,12 +66,6 @@ func InitDB() error {
        // @see https://github.com/mattn/go-sqlite3#faq
        db.SetMaxOpenConns(1)
 
-       // SQLite performance tuning (https://phiresky.github.io/blog/2020/sqlite-performance-tuning/)
-       _, err = db.Exec("PRAGMA journal_mode = WAL; PRAGMA synchronous = normal;")
-       if err != nil {
-               return err
-       }
-
        // create tables if necessary & apply migrations
        if err := dbApplyMigrations(); err != nil {
                return err
```

But probably because `rqlite` database driver is built on JSON API, it is behaving a little bit different than SQLite one, so while testing I needed to add few more changes:

1. mailbox_data.Email saved as base64 (otherwise serialization of `[]byte` to JSON breaks that compressed BLOB)
2. it's unable to `Scan()` SQL INTEGER into Go int64 - probably because it is a number in JSON response and driver is decoding it into `interface{}` or something, therefore `json` package Unmarshal's it into float64.
3. `INSERT RETURNING` clause also didn't work because rqlite disallows to modify data on /query endpoint - `Query()` method is used instead of `Exec()` in code to fetch result - didn't resolve that.

```diff
diff --git a/internal/storage/messages.go b/internal/storage/messages.go
index 03da204..c490e9a 100644
--- a/internal/storage/messages.go
+++ b/internal/storage/messages.go
@@ -4,6 +4,7 @@ import (
        "bytes"
        "context"
        "database/sql"
+       "encoding/base64"
        "encoding/json"
        "errors"
        "fmt"
@@ -102,7 +103,8 @@ func Store(body *[]byte) (string, error) {
 
        // insert compressed raw message
        compressed := dbEncoder.EncodeAll(*body, make([]byte, 0, size))
-       _, err = tx.Exec("INSERT INTO mailbox_data(ID, Email) values(?,?)", id, string(compressed))
+       compressedBase64 := base64.StdEncoding.EncodeToString(compressed)
+       _, err = tx.Exec("INSERT INTO mailbox_data(ID, Email) values(?,?)", id, compressedBase64)
        if err != nil {
                return "", err
        }

@@ -341,7 +343,12 @@ func GetMessageRaw(id string) ([]byte, error) {
                return nil, errors.New("message not found")
        }
 
-       raw, err := dbDecoder.DecodeAll([]byte(msg), nil)
+       msgCompressed, err := base64.StdEncoding.DecodeString(msg)
+       if err != nil {
+               return nil, fmt.Errorf("error base64 decoding message: %w", err)
+       }
+
+       raw, err := dbDecoder.DecodeAll(msgCompressed, nil)
        if err != nil {
                return nil, fmt.Errorf("error decompressing message: %s", err.Error())
        }
```

```diff
@@ -155,7 +157,7 @@ func List(start, limit int) ([]MessageSummary, error) {
                Offset(start)
 
        if err := q.QueryAndClose(nil, db, func(row *sql.Rows) {
-               var created int64
+               var created float64
                var id string
                var messageID string
                var subject string
@@ -176,7 +178,7 @@ func List(start, limit int) ([]MessageSummary, error) {
                        return
                }
 
-               em.Created = time.UnixMilli(created)
+               em.Created = time.UnixMilli(int64(created))
                em.ID = id
                em.MessageID = messageID
                em.Subject = subject
```

**Comment by ulexxander** [comment]
But there are probably a lot more changes required for all Mailpit logic to work normally.

So I got another idea of how to satisfy my use case without need to modify Mailpit:
I will get rid of that PersistentVolume for each Mailpit.
Instead I will add sidecar container for each Mailpit that will be checking SQLite for changes and will be performing backups to some shared storage.
Then on startup (restart) there will be `initContainer` that will download backup and restore it!

I will share solution if I'll succeed.

**Comment by axllent** [comment]
Thanks for the info so far @ulexxander, the implementation you demonstrated is already significantly easier than I had imagined. The need to base64-encode the binary e-mail data however is a bummer, as that would greatly increase the storage size of the database (the whole point of zstd compression is to reduce the db storage size).

Anyway, please keep me in the loop with your progress/solution. Not sure if NFS or something is a feasible alternative (or even possible in Kubernetes), although I think the options I use with sqlite aren't friendly with remote filesystems (that could be conditionally toggled with a startup flag though).

**Comment by axllent** [comment]
@ulexxander Just to keep this issue "alive" (so it's not marked as stale) - any progress on your end? I did see your activity in rqlite so it looks like you are still active :+1:

**Comment by axllent** [comment]
You're totally right, it wasn't you (I incorrectly assumed it was). I guess the author of rqlite may have seen this discussion and thought it was a great idea to promote that implementation. For what it's worth, I believe rsqlite does support blob too (coming back to the earlier base64 comment). I'm actually pretty excited to see the performance of it (I know it won't be as fast as native/local, but I'm really curious as to how it performs over HTTP), and whether it can (almost) wok as a drop-in replacement! 

I am also very busy at the moment with other priorities including work, so haven't had time to look into rsqlite other than a bit of light reading, and besides.... you're doing this piece of work which I really appreciate :-) I've already put in hundreds of hours of work so it's really great to have some help. I have been giving it a lot of thought as to how one could potentially "integrate" it from an end-user perspective without over-complicating the user-options - assuming rsqlite can be integrated as simply a DB driver supporting the same SQL commands,  the existing `--db-file` could be dual-purpose ~if a file path then then use sqlite, else if a URL then rsqlite.  

Anyway, I'll leave this with you. Nice to hear you're still working on it.

**Comment by ulexxander** [comment]
Hello @axllent I implemented my idea - to backup Mailpit's SQLite database to S3 frequently instead of mounting persistent storage into container.

And I am satisfied with it for now, works great.

Sharing it here:

1. Build and push your Docker image including AWS CLI, gzip and sqlite3 (mine has few more utilities).

```Dockerfile
FROM ubuntu:jammy
WORKDIR /build

RUN \
  apt-get update -qq && \
  DEBIAN_FRONTEND="noninteractive" \
  apt-get install -qq -y --no-install-recommends \
  ca-certificates \
  curl \
  jq \
  mc \
  sqlite3 \
  unzip \
  vim \
  zip \
  && apt-get clean

RUN \
  curl -o awscli.zip "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.15.32.zip" && \
  unzip -q awscli.zip && \
  ./aws/install && \
  rm -rf aws awscli.zip

WORKDIR /app
```

2. Create AWS IAM role or user with allowed actions:

- `s3:GetObject`
- `s3:ListBucket`
- `s3:PutObject`

3. Deploy Mailpit with initContainer `db-restore` that will restore last backup and
   sidecar container `db-backup` that will be checking checksum of database and backup it to AWS S3 if changes.
   Adjust `sleep 10` interval for yourself. If you have small Mailpit database like I do, it should be very lightweight.
   Benchmarked it by doing checksums 10 times **per second** with 400KB database - only consumed 0.1 CPU time on `t3.large` instance.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  labels:
    app.kubernetes.io/name: mailpit
spec:
  replicas: 1
  strategy:
    # At most one instance should run during upgrades, because of backup mechanism.
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mailpit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mailpit
    spec:
      # To authenticate with S3 either use ServiceAccount (if you on AWS EKS)
      # or create access token and load it in environment variables of "db-restore" and "db-backup" containers.
      # For EKS: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
      serviceAccountName: mailpit

      imagePullSecrets:
        - name: your-container-registry

      volumes:
        - name: data
          emptyDir: {}

      # Instead of using PersistentVolume and need to create it for each merge request,
      # we will backup database to S3 frequently if it changes and restore latest backup on redeploy.
      initContainers:
        - name: db-restore
          image: your-registry/aws-cli-db:v1
          imagePullPolicy: IfNotPresent
          workingDir: /data
          command:
            - sh
            - -c
            - |-
              set -e
              aws s3 cp s3://${S3_BUCKET}/${S3_OBJECT} mailpit.db.gz || CP_FAIL=true
              if [ "$CP_FAIL" = "true" ]; then echo "Nothing to restore"; exit 0; fi
              gzip -df mailpit.db.gz
              echo "Restored existing database backup"
          env:
            - name: AWS_DEFAULT_REGION
              value: your-aws-region-1
            - name: S3_BUCKET
              value: my-mailpit
            - name: S3_OBJECT
              value: mailpit.db.gz
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              memory: 128Mi

      containers:
        - name: mailpit
          image: axllent/mailpit:v1.15.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: mailpit-smtp
              containerPort: 1025
            - name: mailpit-ui
              containerPort: 8025
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: MP_DATA_FILE
              value: /data/mailpit.db
          readinessProbe:
            tcpSocket:
              port: mailpit-ui
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              memory: 128Mi

        - name: db-backup
          image: your-registry/aws-cli-db:v1
          imagePullPolicy: IfNotPresent
          workingDir: /data
          command:
            - sh
            - -c
            - |-
              set -e
              trap exit TERM
              echo "Starting continuous backup"
              while true; do
                sleep 10 & wait

                OLD_HASH=$(cat mailpit.db.sum || true)
                NEW_HASH=$(sqlite3 mailpit.db ".sha3sum --schema")
                if [ "$NEW_HASH" = "$OLD_HASH" ]; then continue; fi
                echo "Database file has changed, performing backup"
                echo "Old: $OLD_HASH"
                echo "New: $NEW_HASH"

                sqlite3 mailpit.db ".backup mailpit.db.bak"
                gzip -kf mailpit.db.bak
                aws s3 cp mailpit.db.bak.gz s3://${S3_BUCKET}/${S3_OBJECT}
                echo "$NEW_HASH" > mailpit.db.sum
              done
          env:
            - name: AWS_DEFAULT_REGION
              value: your-aws-region-1
            - name: S3_BUCKET
              value: my-mailpit
            - name: S3_OBJECT
              value: mailpit.db.gz
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              memory: 128Mi
```
