### ISSUE TITLE
Docker up failure? "disk I/O error (5386)" mailpit exited with code 1

### ISSUE THREAD

**Issue by epicwhale** [axllent/mailpit#271]
Following the docker compose example: https://mailpit.axllent.org/docs/install/docker/

```
    mailpit:
        image: axllent/mailpit:latest
        container_name: mailpit
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATA_FILE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
```

When I up it:

```
docker compose up mailpit
[+] Running 1/0
 ✔ Container mailpit  Created                                                                                                                                                   0.0s 
Attaching to mailpit
mailpit  | time="2024/03/30 09:15:35" level=error msg="disk I/O error (5386)"
mailpit exited with code 1
```

Any pointers to resolving this?
