### ISSUE TITLE
Configuring tags via config-file does not work

### ISSUE THREAD

**Issue by ppasieka** [axllent/mailpit#331]
I'm trying to configure the automatic tags assignment to emails.

My docker-compose looks like:

```yaml
  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - ./mailpit-config.yaml:/config/mailpit-config.yaml
    environment:
      - MP_TAGS_CONFIG=/config/mailpit-config.yaml
```

And my `mailpit-config.yaml` looks like

```yaml
filters:
  - match: [error-internal-server-error]
    keywords: EXCEPTION
  - match: [error-invalid-request]
    keywords: BAD REQUEST
```

I tried different variations on the match phrases (no braces, only single words, etc.), but nothing worked. 

In the Mailpit application logs, I can see the following:

```
2024-07-07 13:29:22 time="2024/07/07 11:29:22" level=warning msg="[tags] invalid tag () - can only contain spaces, letters, numbers, - & _"
2024-07-07 13:29:22 time="2024/07/07 11:29:22" level=warning msg="[tags] invalid tag () - can only contain spaces, letters, numbers, - & _"
2024-07-07 13:29:22 time="2024/07/07 11:29:22" level=info msg="[smtpd] starting on [::]:1025 (no encryption)"
2024-07-07 13:29:22 time="2024/07/07 11:29:22" level=info msg="[http] starting on [::]:8025"
2024-07-07 13:29:22 time="2024/07/07 11:29:22" level=info msg="[http] accessible via http://localhost:8025/"
```

When I use the environment variables to set tags, then tagging to works

```yaml
  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MP_TAG="EXCEPTION=subject:[error-internal-server-error]"
```

Am I doing something wrong?

**Comment by ppasieka** [comment]
short python script to help test this out

```python
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import random
import string

def generate_random_email():
    username = ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))
    domain = ''.join(random.choices(string.ascii_lowercase, k=6))
    return f"{username}@{domain}.com"

def generate_random_message():
    words = ['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
    return ' '.join(random.choices(words, k=random.randint(5, 10)))

def send_email(subject, from_addr, to_addr, body):
    msg = MIMEMultipart()
    msg['From'] = from_addr
    msg['To'] = to_addr
    msg['Subject'] = subject

    msg.attach(MIMEText(body, 'plain'))

    server = smtplib.SMTP('localhost', 1025)
    text = msg.as_string()
    server.send_message(msg)
    server.quit()

    print(f"Sent email: \nFrom: {from_addr}\nTo: {to_addr}\nSubject: {subject}\nBody: {body}\n")

def main():
    to_address = "test@example.com"  # You can change this to any email address

    # Send email with [error-internal-server-error] in subject
    send_email(
        subject="Hey! [error-internal-server-error] Test Email",
        from_addr=generate_random_email(),
        to_addr=to_address,
        body=generate_random_message()
    )

    # Send email with [error-invalid-request] in subject
    send_email(
        subject="Hey! [error-invalid-request] Another Test Email",
        from_addr=generate_random_email(),
        to_addr=to_address,
        body=generate_random_message()
    )

    # Send a normal email without special subject
    send_email(
        subject="Normal Test Email",
        from_addr=generate_random_email(),
        to_addr=to_address,
        body=generate_random_message()
    )

if __name__ == "__main__":
    main()
```

**Comment by ppasieka** [comment]
Ok. I found what is wrong: the documentation is outdated.

The YAML parser for tags expects the `tags` as a key, not `keywords` key:

```go
type yamlTags struct {
	Filters []yamlTag `yaml:"filters"`
}

type yamlTag struct {
	Match string `yaml:"match"`
	Tags  string `yaml:"tags"`
}
```

Changing my `mailpit-config.yaml` content to:

```yaml
filters:
  - match: error-internal-server-error
    tags: EXCEPTION
  - match: error-invalid-request
    tags: BAD REQUEST
``` 
And this makes it work!
