### ISSUE TITLE
Documentation about tags

### ISSUE THREAD

**Issue by blackshot** [axllent/mailpit#332]
I'm currently trying to implement mailpit as a developer centralized mail sandbox for all my mails, in order to effectively do that i need to implement automatic tags, i made a yaml file as documentation says, it loads the tags but none of the emails are being tagged. 

i couldn't find any documentation of how to build a matcher. even i tried to find it in source code but couldn't find anything.

EDIT: I somehow made it work using matcher "addressed:..." but "from:..." is not working.

**Comment by axllent** [comment]
Hi @blackshot.

I cannot really make any comment without seeing the exact filter syntax you are using.

The following types of filter rules should work (you'll see both uses of `addressed:` and `from:` which work as expected for me):
```yaml
filters:
  - match: addressed:accounts@example.com
    tags: Accounts
  - match: from:notifications@github.com
    tags: Github
  - match: from:@github.com subject:axllent/mailpit
    tags: Github, Mailpit
```
This is [documented here](https://mailpit.axllent.org/docs/usage/tagging/#set-filters-using---tag). The match is exactly the same as you would use in the web UI to search/filter messages, which is [documented here](https://mailpit.axllent.org/docs/usage/search-filters/).
