### ISSUE TITLE
While running in docker, the server sometimes hangs and the client times out

### ISSUE THREAD

**Issue by adibsaad** [axllent/mailpit#351]
I'm running it in docker like this

```
  mailpit:
    image: axllent/mailpit:v1.20.2
    container_name: mailpit
    volumes:
      - mailpit-data:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
        MP_DATA_FILE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
        MP_VERBOSE: 1
```

and I noticed that sometimes, the server seems to hang and emails don't go through, and my app times out. After it times out I'll see this line in the mailpit log

```
mailpit  | time="2024/08/19 21:24:22" level=debug msg="[smtpd] response (192.168.228.1) 220 2392b9ce4ed7 Mailpit ESMTP Service ready"
```
