### ISSUE TITLE
Spamassassin ALL_TRUSTED

### ISSUE THREAD

**Issue by otbutz** [axllent/mailpit#381]
docker-compose.yml:

```yml
services:
  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit-data:/data
    ports:
      - 80:8025
      - 25:1025
    environment:
      MP_ENABLE_SPAMASSASSIN: spamassassin:783
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      TZ: Europe/Berlin
    depends_on:
      - spamassassin
  spamassassin:
    container_name: spamassassin
    image: axllent/spamassassin
    restart: unless-stopped
```

Sending a test mail to Mailpit results in an overly optimistic spam result:

![image](https://github.com/user-attachments/assets/7c051c4a-7f27-40ca-9308-aa86cb40a705)
