### ISSUE TITLE
SMTP doesn't support AUTH

### ISSUE THREAD

**Issue by KaptinLin** [axllent/mailpit#4]
Hi, I got a error when send via smtp

```
smtp: server doesn't support AUTH
```

**Comment by axllent** [comment]
The SMTP server doesn't currently support authentication, it's just open/non-encrypted. Can you please tell me your use-case and requirements?

**Comment by KaptinLin** [comment]
Some [lib check username and password](https://github.com/ainsleyclark/go-mail/blob/main/drivers/smtp.go#L50), and it using `smtp.PlainAuth` send emails. If i don't fill username and password, it just dont work.

Another node.js based app [maildev](https://github.com/maildev/maildev) can work with it. But if you can support it that would be better.
```
maildev:
    image: maildev/maildev:latest
    environment:
      MAILDEV_INCOMING_USER: "hello@example.com"
      MAILDEV_INCOMING_PASS: "password"
    ports:
      - "1080:1080"
      - "1025:1025"
 ```
