### ISSUE TITLE
Mailpit in crashloopbackoff error in Kubernetes

### ISSUE THREAD

**Issue by wali97** [axllent/mailpit#401]
Hi,
I've deployed mailpit as a deployment in my GKE cluster with following configuration,no authentication or anything is enabled,

```
 env:
        - name: MP_DATABASE
          value: /data/mailpit.db
        - name: MP_MAX_MESSAGES
          value: '5000'
        - name: MP_SMTP_AUTH_ACCEPT_ANY
          value: '1'
        - name: MP_SMTP_AUTH_ALLOW_INSECURE
          value: '1'
```

It runs for sometime,but then mailpit pod goes into crashloopbackoff error
`level=fatal msg="database is locked (5) (SQLITE_BUSY)"`

I tried using three different mailpit docker images with version v1.20.7,v1.21.3,v1.21.5 but all result in same error. 
Can please help me out on this as to why i keep getting this error.
