### ISSUE TITLE
mailpit.svg file not found when webroot is set

### ISSUE THREAD

**Issue by Lyrkan** [axllent/mailpit#441]
Hi there,

Since version 1.22.2 it seems that the mailpit.svg file cannot be loaded when using a webroot.

**Using v1.22.2 without a webroot:**

```
services:
  mailpit:
    image: axllent/mailpit:v1.22.2
    ports:
      - '8025:8025'
```

```
$ curl http://127.0.0.1:8025/mailpit.svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="500"
   height="460"
(...)
```

**Using v1.22.2 with a webroot:**

```
services:
  mailpit:
    image: axllent/mailpit:v1.22.2
    ports:
      - '8025:8025'
    environment:
      MP_WEBROOT: '/mailpit/'
```

```
$ curl http://127.0.0.1:8025/mailpit/mailpit.svg
File not found
```

**Using v1.22.1 with a webroot:**

```
services:
  mailpit:
    image: axllent/mailpit:v1.22.1
    ports:
      - '8025:8025'
    environment:
      MP_WEBROOT: '/mailpit/'
```

```
$ curl http://127.0.0.1:8025/mailpit/mailpit.svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   width="500"
   height="460"
(...)
```
