### ISSUE TITLE
SMTP Relay Timeout Blocks Client Connection Until External Timeout

### ISSUE THREAD

**Issue by Lunaden** [axllent/mailpit#517]
### Description

We are using **Mailpit as an SMTP relay in a test environment**, configured via Docker:

```yaml
services:
  smtp-relay:
    image: axllent/mailpit
    restart: always
    ports:
      - "25:25"
    networks:
      - smtp
      - proxy
    volumes:
      - /containers/mailpit/config:/config:ro
      - /containers/mailpit/data:/data
    environment:
      TIMEZONE: Europe/Paris
      TZ: Europe/Paris
      MP_SMTP_RELAY_CONFIG: /config/smtp-relay.cfg
      MP_SMTP_RELAY_ALL: 'true'
      MP_SMTP_MAX_RECIPIENTS: 20
      MP_SMTP_DISABLE_RDNS: 'true'
      MP_ALLOW_UNTRUSTED_TLS: 'true'
      MP_MAX_MESSAGES: 10000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_BIND_ADDR: '0.0.0.0:25'
```

The service works well in most cases. However, we have noticed that when Mailpit attempts to relay to certain **external SMTP servers** (e.g., `mail.example.com:25`), it sometimes encounters **connection timeouts**, and during this time the client that initiated the email remains **blocked until the timeout occurs**.

Here are sample logs showing the issue:

```
time="2025/06/10 18:15:16" level=error msg="[smtp] error relaying message: error connecting to mail.example.com:25: dial tcp 52.101.xxx.xxx:25: connect: connection timed out"
...
time="2025/06/10 18:33:01" level=error msg="[smtp] error relaying message: error connecting to mail.example.com:25: dial tcp 52.101.xxx.xxx:25: connect: connection timed out"
```

---

### Expected Behavior

Mailpit should accept the message from the SMTP client and respond immediately, **even if the relay target is unreachable**, handling the external delivery **asynchronously**.

---

### Actual Behavior

When the relay fails (e.g., connection timeout), the SMTP client is kept waiting until the timeout completes. This causes blocking behavior in our upstream systems.

---

### Context

This behavior is observed in a **test environment**, so the impact is currently limited. However, it is still disruptive during development, testing, and performance benchmarking, and would be **problematic in a production setup**.

---

### Questions

* Is this synchronous relay behavior expected by design?
* Is there a way to configure Mailpit to **immediately accept client messages and handle relay in the background** (queue-first)?
* If not, would it be possible to consider this as a feature request?

---

### Environment

* **Mailpit image**: `axllent/mailpit`
* **Environment**: Docker on Linux
* **SMTP bind port**: 25
* **Relay target**: Third-party gateway

---
