### ISSUE TITLE
`MP_SMTP_AUTH_ALLOW_INSECURE` can not be configured via env variable

### ISSUE THREAD

**Issue by IgnisDa** [axllent/mailpit#77]
I set `MP_SMTP_AUTH_ALLOW_INSECURE = 1` in my environment.

I get this error.

```
ERRO[2023/03/31 16:13:13] SMTP authentication requires TLS encryption, run with `--smtp-auth-allow-insecure` to allow insecure authentication
```

I think it means that the enviroment variable is not being recognized.

Same applies to the `MP_SMTP_AUTH_ACCEPT_ANY` variable.

**Comment by axllent** [comment]
Can you please cop & paste the exact command you are running to start Mailpit, including trying to set the environment?

**Comment by IgnisDa** [comment]
I have this in my `docker-compose.yml`.

```yml

  mail:
    image: axllent/mailpit
    ports:
      - 8025:8025
    environment:
      MP_DATA_FILE: /data/mail.data
      MP_SMTP_AUTH_ACCEPT_ANY: '1'
      MP_SMTP_AUTH_ALLOW_INSECURE: '1'
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025/readyz" ]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - mail-data:/data
```
