### ISSUE TITLE
Automatically reload/refresh inbox in UI

### ISSUE THREAD

**Issue by D3strukt0r** [axllent/mailpit#93]
The company I work for has recently switched over to your tool, and there is certainly one feature I have been missing, which is that the inbox reloads automatically. If I immediatly saw that a new mail came in, it would hinder my development process less. Maybe make it configurable or something.

**Comment by axllent** [comment]
Hi @D3strukt0r. This feature already exists and is always enabled. If I had to take a calculated guess, you are accessing the Mailpit http server via a proxy, an I right (eg: Apache it Nginx)? Can toyt confirm please?

**Comment by D3strukt0r** [comment]
@axllent  Oh I didn't know that, then I don't know what I am missing. We are using an Nginx Proxy, pretty simple one

`docker-compose.yml`
```yaml
services:
  mailcatcher:
    image: axllent/mailpit:latest
    init: true
    container_name: mailcatcher
    domainname: local
    networks:
      - appnetwork
  mailcatcher_https:
    image: nginx:latest
    init: true
    container_name: mailcatcher_https
    ports:
      - '1080:443'
    environment:
      NGINX_PROXY: mailcatcher:8025
    volumes:
      - ./certificates:/etc/ssl/certs/local:ro
      - ../build-local/assets-nginx-https-proxy/default.conf:/etc/nginx/templates/default.conf.template
    links:
      - mailcatcher
    networks:
      - appnetwork
```

`default.conf`
```nginx
upstream upstream {
    server ${NGINX_PROXY};
}

server {
    listen 80 default_server;
    server_name _;

    location / {
        return 302 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2 default_server;
    server_name _;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
    ssl_certificate /etc/ssl/certs/local/cert.pem;
    ssl_certificate_key /etc/ssl/certs/local/key.pem;

    client_max_body_size 100M;

    location / {
        proxy_pass http://upstream/;

        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
    }
}
```

**Comment by D3strukt0r** [comment]
@axllent 

ok so switched to your own ssl config and works with that

```yaml
  mailcatcher:
    image: axllent/mailpit:latest
    init: true
    container_name: mailcatcher
    domainname: local
    ports:
      - '1080:8025'
    environment:
      MP_UI_TLS_CERT: /etc/ssl/certs/local/cert.pem
      MP_UI_TLS_KEY: /etc/ssl/certs/local/key.pem
    volumes:
      - ./certificates:/etc/ssl/certs/local:ro
    networks:
      - appnetwork
```
